// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cktriqnfikxxjfaceato.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrdHJpcW5maWt4eGpmYWNlYXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMDIxOTgsImV4cCI6MjA3MzY3ODE5OH0.hVL_eoEYb-8s3c-z6C80DzZmlHh2qQ5l2bHFhwwDiVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});